# Generated by Django 4.1.5 on 2023-01-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options_users_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='img',
        ),
    ]
