# Generated by Django 4.1.5 on 2023-02-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='author',
        ),
    ]
