# Generated by Django 4.1.6 on 2023-02-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customers_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='customer_name',
        ),
    ]
