# Generated by Django 4.1.6 on 2023-02-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_name_customers_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='customer_name',
            new_name='name',
        ),
    ]
