# Generated by Django 4.1.6 on 2023-02-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_customer_name_customers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='img',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
