# Generated by Django 4.1.6 on 2023-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_dashboard_alter_customers_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboard',
            new_name='Dashboard_buttons',
        ),
    ]
