# Generated by Django 4.1.5 on 2023-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_dashboard_dashboard_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=50)),
            ],
        ),
    ]
