# Generated by Django 4.1.5 on 2023-02-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='dark_mode',
            field=models.BooleanField(),
        ),
    ]
