# Generated by Django 4.1.5 on 2023-03-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_settings_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='color',
            field=models.CharField(default='#6096B4', max_length=50),
            preserve_default=False,
        ),
    ]
