# Generated by Django 4.1.5 on 2023-03-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_settings_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='color',
            new_name='back_color',
        ),
        migrations.AddField(
            model_name='settings',
            name='primary_color',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
