# Generated by Django 4.1.5 on 2023-05-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_tree_customers_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tree',
            new_name='Accounts',
        ),
    ]
