# Generated by Django 4.1.5 on 2023-05-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_links_subject_id_links_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='subject_name',
            new_name='subject_id',
        ),
    ]
