# Generated by Django 4.1.6 on 2023-05-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_links_description'),
    ]

    operations = [
  
    ]
