# Generated by Django 4.1.6 on 2023-05-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_links_created_at_links_updated_at_and_more'),
    ]

    operations = [

    ]
