# Generated by Django 4.1.6 on 2023-05-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_links_created_at_links_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='links',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='updated_at',
        ),
    ]
