# Generated by Django 4.1.6 on 2023-05-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_subjects_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='time',
        ),
    ]
