# Generated by Django 4.1.6 on 2023-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_subjects_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
