# Generated by Django 4.1.6 on 2023-05-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_rename_subject_name_subjects_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
