# Generated by Django 4.1.6 on 2023-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_subjects_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
