# Generated by Django 4.1.6 on 2023-05-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_links_timestamp_subjects_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
