# Generated by Django 4.1.6 on 2023-05-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_alter_links_timestamp_alter_subjects_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
