# Generated by Django 4.1.6 on 2023-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_links_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
